### ISSUE TITLE
Injection and Provider Lookup Should Account for Qualifiers

### ISSUE THREAD

**Issue by JakeWharton** [square/dagger-intellij-plugin#2]
```java
@Provide @Fast Heater ...
// and
@Provide @Slow Header ...
```

are different things.

**Comment by mattlogan** [comment]
This issue was apparently fixed shortly after it was created, with [this commit](https://github.com/square/dagger-intellij-plugin/commit/5dd0a27ef4bceb811cf9cc0e47c1ebd5102dbfb7) being the last of a series. Should this be closed now?

**Comment by JakeWharton** [comment]
Yep!
