### ISSUE TITLE
Support the last version of Android Studio with Dagger 2

### ISSUE THREAD

**Issue by YvgenTroshchiy** [square/dagger-intellij-plugin#30]

**Comment by YvgenTroshchiy** [comment]
Hello guys,
Are you going to fix this plugin for the last version of Android Studio and dagger 2?
It will be so great!

**Comment by JakeWharton** [comment]
No plans, no. If you have a specific problem please file specific bugs. There's already some Dagger 2 ones like #25.

**Comment by YvgenTroshchiy** [comment]
Got it, it's very sad.
Unfortunately this plugin does not work at all anymore with AS 3.0.1 and Google Dagger 2.14.1
